{
 "title": "Cluster-TiCDC-Summary",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "k8s_cluster",
    "label": "K8s-cluster",
    "query": {
     "query": "label_values(go_goroutines, k8s_cluster)"
    }
   },
   {
    "name": "tidb_cluster",
    "label": "tidb_cluster",
    "query": {
     "query": "label_values(go_goroutines{k8s_cluster=\"$k8s_cluster\"}, tidb_cluster)"
    }
   },
   {
    "name": "changefeed",
    "label": "Changefeed",
    "query": {
     "query": "label_values(ticdc_processor_resolved_ts{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}, changefeed)"
    }
   },
   {
    "name": "ticdc_instance",
    "label": "TiCDC",
    "query": {
     "query": "label_values(process_start_time_seconds{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", job=\"ticdc\"}, instance)"
    }
   },
   {
    "name": "tikv_instance",
    "label": "TiKV",
    "query": {
     "query": "label_values(tikv_engine_size_bytes{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}, instance)"
    }
   },
   { "name": "spike_threshold", "label": "Latency spike (s) >", "query": "1, 3, 5, 10, 60, 300" },
   {
    "name": "runtime_instance",
    "label": "Runtime metrics",
    "query": {
     "query": "label_values(process_start_time_seconds{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", job=\"ticdc\"}, instance)"
    }
   },
   {
    "name": "actor_name",
    "label": "Actor",
    "query": {
     "query": "label_values(ticdc_actor_number_of_workers{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", job=\"ticdc\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Uptime",
     "type": "graph",
     "description": "Uptime of TiCDC and TiKV",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "(time() - process_start_time_seconds{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", job=\"ticdc\"})",
       "legendFormat": "TiCDC-{{instance}}"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "graph",
     "description": "CPU usage of TiCDC",
     "gridPos": { "h": 7, "w": 7, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", job=\"ticdc\"}[1m])",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "ticdc_server_go_max_procs{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", job=\"ticdc\"}",
       "legendFormat": "{{instance}}-MaxProcs"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "graph",
     "description": "Memory usage of TiCDC",
     "gridPos": { "h": 7, "w": 7, "x": 15, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", job=\"ticdc\"}",
       "legendFormat": "process-{{instance}}"
      },
      {
       "expr": "go_memstats_heap_alloc_bytes{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", job=\"ticdc\"}",
       "legendFormat": "heap-{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Changefeed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Changefeed checkpoint lag",
     "type": "graph",
     "description": "The lag between changefeed checkpoint ts and the latest ts of upstream TiDB.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(ticdc_owner_checkpoint_ts_lag{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}) by (changefeed)",
       "legendFormat": "{{changefeed}}"
      }
     ]
    },
    {
     "title": "Changefeed resolved ts lag",
     "type": "graph",
     "description": "The lag between changefeed resolved ts and the latest ts of upstream TiDB.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(ticdc_owner_resolved_ts_lag{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}) by (changefeed)",
       "legendFormat": "{{changefeed}}"
      }
     ]
    },
    {
     "title": "The status of changefeeds",
     "type": "timeseries",
     "description": "The status of each changefeed.\n\n0: Normal\n\n1: Error\n\n2: Failed\n\n3: Stopped\n\n4: Finished\n\n-1: Unknown",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(ticdc_owner_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}) by (changefeed)",
       "legendFormat": "{{changefeed}}"
      }
     ]
    },
    {
     "title": "Exit error count/m",
     "type": "graph",
     "description": "The number of errors that interrupt changefeed per minute ",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ticdc_processor_exit_with_error_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",instance=~\"$ticdc_instance\"}[1m])) by (instance, changefeed)",
       "legendFormat": "{{instance}}-{{changefeed}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dataflow",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Puller output events/s",
     "type": "graph",
     "description": "The number of events that puller outputs to sorter \n per second",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum (rate(ticdc_puller_txn_collect_event_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", instance=~\"$ticdc_instance\"}[1m])) by (changefeed, instance, type)",
       "legendFormat": "{{changefeed}}-{{instance}}-{{type}}"
      }
     ]
    },
    {
     "title": "Puller output events",
     "type": "graph",
     "description": "The total number of events that puller outputs",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(ticdc_puller_txn_collect_event_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", instance=~\"$ticdc_instance\"}) by (changefeed, instance, type)",
       "legendFormat": "{{changefeed}}-{{instance}}-{{type}}"
      }
     ]
    },
    {
     "title": "Sorter output events/s",
     "type": "graph",
     "description": "The number of events that sorter outputs to puller \n per second",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ticdc_sorter_output_event_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", instance=~\"$ticdc_instance\"}[1m])) by (changefeed, instance, type)",
       "legendFormat": "{{changefeed}}-{{instance}}-{{type}}"
      }
     ]
    },
    {
     "title": "Sorter output events",
     "type": "graph",
     "description": "The total number of events that sorter outputs",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(ticdc_sorter_output_event_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", instance=~\"$ticdc_instance\"}) by (instance, changefeed, type)",
       "legendFormat": "{{changefeed}}-{{instance}}-{{type}}"
      }
     ]
    },
    {
     "title": "Mounter output events/s",
     "type": "graph",
     "description": "The number of events that mounter outputs to sink per second",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ticdc_mounter_total_rows_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", instance=~\"$ticdc_instance\"}[1m])) by (instance,changefeed)",
       "legendFormat": "{{changefeed}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Mounter output events",
     "type": "graph",
     "description": "The total number of events that mounter outputs",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(ticdc_mounter_total_rows_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", instance=~\"$ticdc_instance\"}) by (changefeed, instance)",
       "legendFormat": "{{changefeed}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Sink flush rows/s",
     "type": "graph",
     "description": "The number of rows that sink flushes to downstream per second.",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ticdc_sink_batch_row_count_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", instance=~\"$ticdc_instance\"}[1m])) by (changefeed, instance)",
       "legendFormat": "{{changefeed}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Sink flush rows",
     "type": "graph",
     "description": "The number of rows(events) that are flushed by sink.",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(ticdc_sink_batch_row_count_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}) by (changefeed, instance)",
       "legendFormat": "{{changefeed}}-{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Transaction Sink",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Backend Flush Duration",
     "type": "graph",
     "description": "Sink worker busy ratio",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(ticdc_sink_txn_sink_dml_batch_commit_bucket{k8s_cluster=\"$k8s_cluster\",tidb_cluster=\"$tidb_cluster\"}[1m])) by (le,changefeed,instance))",
       "legendFormat": "99.9-{{changefeed}}-{{instance}}"
      },
      {
       "expr": "sum(rate(ticdc_sink_txn_sink_dml_batch_commit_sum{k8s_cluster=\"$k8s_cluster\",tidb_cluster=\"$tidb_cluster\"}[1m])) by (changefeed,instance) / \nsum(rate(ticdc_sink_txn_sink_dml_batch_commit_count{k8s_cluster=\"$k8s_cluster\",tidb_cluster=\"$tidb_cluster\"}[1m])) by (changefeed,instance)",
       "legendFormat": "avg-{{changefeed}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Full Flush Duration",
     "type": "graph",
     "description": "Full flush (backend flush + callback + conflict detector notify) duration",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(ticdc_sink_txn_worker_flush_duration_bucket{k8s_cluster=\"$k8s_cluster\",tidb_cluster=\"$tidb_cluster\"}[1m])) by (le,changefeed,instance))",
       "legendFormat": "99.9-{{changefeed}}-{{instance}}"
      },
      {
       "expr": "sum(rate(ticdc_sink_txn_worker_flush_duration_sum{k8s_cluster=\"$k8s_cluster\",tidb_cluster=\"$tidb_cluster\"}[1m])) by (changefeed,instance) / \nsum(rate(ticdc_sink_txn_worker_flush_duration_count{k8s_cluster=\"$k8s_cluster\",tidb_cluster=\"$tidb_cluster\"}[1m])) by (changefeed,instance)",
       "legendFormat": "avg-{{changefeed}}-{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MQ Sink",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Worker Send Message Duration Percentile",
     "type": "graph",
     "description": "MQ worker send messages to Kafka, this metric record the time cost on send every message.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(ticdc_sink_mq_worker_send_message_duration_bucket{k8s_cluster=\"$k8s_cluster\",tidb_cluster=\"$tidb_cluster\"}[1m])) by (le,changefeed,instance))",
       "legendFormat": "{{changefeed}}-{{instance}}-P999"
      },
      {
       "expr": "sum(rate(ticdc_sink_mq_worker_send_message_duration_sum{k8s_cluster=\"$k8s_cluster\",tidb_cluster=\"$tidb_cluster\"}[1m])) by (changefeed,instance) / \nsum(rate(ticdc_sink_mq_worker_send_message_duration_count{k8s_cluster=\"$k8s_cluster\",tidb_cluster=\"$tidb_cluster\"}[1m])) by (changefeed,instance)",
       "legendFormat": "{{changefeed}}-{{instance}}-avg"
      }
     ]
    },
    {
     "title": "Kafka Outgoing Bytes",
     "type": "graph",
     "description": "Bytes/second written off all brokers.\nvalue = one-minute moving average rate of Bytes per second",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(ticdc_sink_kafka_producer_outgoing_byte_rate{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\", instance=~\"$ticdc_instance\"}) by (changefeed, instance, broker)",
       "legendFormat": "{{changefeed}}-{{instance}}-{{broker}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cloud Storage Sink",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Write Bytes/s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ticdc_sink_cloud_storage_write_bytes_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",instance=~\"$ticdc_instance\"}[1m])) by (changefeed, instance)\n",
       "legendFormat": "{{changefeed}}-{{instance}}"
      }
     ]
    },
    {
     "title": "File Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(ticdc_sink_cloud_storage_file_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}) by (changefeed, instance)",
       "legendFormat": "{{changefeed}}-{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Redo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Redo Write rows/s ",
     "type": "graph",
     "description": "The total count of rows that are processed by redo writer",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ticdc_redo_total_rows_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",instance=~\"$ticdc_instance\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(rate(ticdc_redo_total_rows_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\"}[1m])) by (changefeed)",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Redo Write bytes/s ",
     "type": "graph",
     "description": "Total number of bytes redo log written",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ticdc_redo_write_bytes_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",instance=~\"$ticdc_instance\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Redo flush log duration",
     "type": "heatmap",
     "description": "The latency distributions of flushLog called by redoManager",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "max(rate(ticdc_redo_flush_log_duration_seconds_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",instance=~\"$ticdc_instance\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Redo flushall duration",
     "type": "heatmap",
     "description": "The latency distributions of flushall called by redo writer",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "max(rate(ticdc_redo_flushall_duration_seconds_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", changefeed=~\"$changefeed\",instance=~\"$ticdc_instance\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}