{
 "title": "Cluster-PD",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "k8s_cluster",
    "label": "K8s-cluster",
    "query": {
     "query": "label_values(pd_cluster_status, k8s_cluster)"
    }
   },
   {
    "name": "tidb_cluster",
    "label": "tidb_cluster",
    "query": {
     "query": "label_values(pd_cluster_status{k8s_cluster=\"$k8s_cluster\"}, tidb_cluster)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(pd_cluster_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}, instance)"
    }
   },
   {
    "name": "store",
    "label": "store",
    "query": {
     "query": "label_values(pd_scheduler_store_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}, store)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "PD role",
   "type": "stat",
   "description": "It indicates whether the current PD is the leader or a follower.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pd_tso_role{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\", dc=\"global\"}"
    }
   ]
  },
  {
   "title": "Storage capacity",
   "type": "stat",
   "description": "The total capacity size of the cluster",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pd_cluster_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\",type=\"storage_capacity\"})"
    }
   ]
  },
  {
   "title": "Current storage size",
   "type": "stat",
   "description": "The current storage size of the cluster",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pd_cluster_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\",type=\"storage_size\"})"
    }
   ]
  },
  {
   "title": "Current storage used",
   "type": "gauge",
   "description": "The current storage size and used ratio of the cluster",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pd_cluster_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\",type=\"storage_size\"}) / sum(pd_cluster_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\",type=\"storage_capacity\"})"
    }
   ]
  },
  {
   "title": "Normal stores",
   "type": "stat",
   "description": "The count of healthy stores",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pd_cluster_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\",  type=\"store_up_count\"})"
    }
   ]
  },
  {
   "title": "Number of Regions",
   "type": "stat",
   "description": "The total number of Regions without replicas",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pd_cluster_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\",type=\"leader_count\"})"
    }
   ]
  },
  {
   "title": "Abnormal stores",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(pd_cluster_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\", type=\"store_disconnected_count\"})",
     "legendFormat": "Disconnect Stores"
    },
    {
     "expr": "sum(pd_cluster_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\", type=\"store_unhealth_count\"})",
     "legendFormat": "Unhealth Stores"
    },
    {
     "expr": "sum(pd_cluster_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\", type=\"store_low_space_count\"})",
     "legendFormat": "LowSpace Stores"
    },
    {
     "expr": "sum(pd_cluster_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\", type=\"store_down_count\"})",
     "legendFormat": "Down Stores"
    },
    {
     "expr": "sum(pd_cluster_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\", type=\"store_offline_count\"})",
     "legendFormat": "Offline Stores"
    },
    {
     "expr": "sum(pd_cluster_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\", type=\"store_tombstone_count\"})",
     "legendFormat": "Tombstone Stores"
    },
    {
     "expr": "sum(pd_cluster_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\", type=\"store_slow_count\"})",
     "legendFormat": "Slow Stores"
    }
   ]
  },
  {
   "title": "Region health",
   "type": "graph",
   "description": "It records the unusual Regions' count which may include pending peers, down peers, extra peers, offline peers, missing peers or learner peers",
   "gridPos": { "h": 7, "w": 11, "x": 5, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pd_regions_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "pd_regions_offline_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=\"offline-peer-region-count\", instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Current peer count",
   "type": "graph",
   "description": "The current peer count of the cluster",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(pd_cluster_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\",  type=\"region_count\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Offline store progress",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(pd_cluster_progress{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\", action=\"removing\"} > 0)"
    }
   ]
  },
  {
   "title": "Online store progress",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(pd_cluster_progress{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\", action=\"preparing\"} > 0)"
    }
   ]
  },
  {
   "title": "Left time",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pd_cluster_eta{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\"}",
     "legendFormat": "{{action}}-{{store}}"
    }
   ]
  },
  {
   "title": "Current scaling speed",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "pd_cluster_speed{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\"}",
     "legendFormat": "{{action}}-{{store}}"
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "PD scheduler config",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "pd_config_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Store limit",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 5, "x": 4, "y": 20 },
     "targets": [
      { "expr": "pd_cluster_store_limit" }
     ]
    },
    {
     "title": "Cluster ID",
     "type": "table-old",
     "gridPos": { "h": 3, "w": 5, "x": 9, "y": 20 },
     "targets": [
      {
       "expr": "pd_cluster_metadata{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Region label isolation level",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 5, "x": 14, "y": 20 },
     "targets": [
      {
       "expr": "pd_regions_label_level{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Label distribution",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 20 },
     "targets": [
      {
       "expr": "pd_cluster_placement_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Current ID allocation",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 9, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "pd_cluster_id{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\", type=\"idalloc\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "PD cpu usage calculated with process cpu running seconds",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\",job=~\".*pd.*\"}[30s])",
       "legendFormat": "{{job}}-{{instance}}"
      },
      {
       "expr": "pd_service_maxprocs{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\",job=~\".*pd.*\"}",
       "legendFormat": "{{job}}-{{instance}}-limit"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "description": "PD  memory usage. ",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\",job=~\".*pd.*\"}",
       "legendFormat": "process-{{job}}-{{instance}}"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\",job=~\".*pd.*\"}",
       "legendFormat": "HeapInuse-{{job}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "graph",
     "description": "PD uptime since last restart",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "(time() - process_start_time_seconds{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\",job=~\".*pd.*\"})",
       "legendFormat": "{{job}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Goroutine Count",
     "type": "graph",
     "description": "PD process current goroutines count",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\",job=~\".*pd.*\"}",
       "legendFormat": "{{job}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Current TSO Physcial",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "pd_cluster_tso{instance=\"$instance\", type=\"tso\", dc=\"global\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Max TSO gap",
     "type": "graph",
     "description": "The gap between TSO and current time",
     "gridPos": { "h": 8, "w": 7, "x": 5, "y": 41 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(pd_cluster_tso_gap_millionseconds{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\"}) by (dc)",
       "legendFormat": "{{dc}}"
      }
     ]
    },
    {
     "title": "Current TSO Datetime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "pd_cluster_tso{instance=\"$instance\", type=\"tso\", dc=\"global\"}",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Operator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Schedule operator create",
     "type": "graph",
     "description": "The number of different operators that are newly created",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_schedule_operators_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\", event=\"create\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Schedule operator check",
     "type": "graph",
     "description": "The number of different operators that have been checked. It mainly checks if the current step is finished; if yes, it returns the next step to be executed.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_schedule_operators_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\", event=\"check\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Schedule operator finish",
     "type": "graph",
     "description": "The number of different operators that are finished",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_schedule_operators_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\", event=\"finish\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Schedule operator timeout",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_schedule_operators_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\", event=\"timeout\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Schedule operator replaced or canceled",
     "type": "graph",
     "description": "The number of different operators that are replaced or canceled",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_schedule_operators_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\", event=\"cancel\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(delta(pd_schedule_operators_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\", event=\"replace\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Schedule operators count by state",
     "type": "graph",
     "description": "The number of operators in different status",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_schedule_operators_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\"}[1m])) by (event)",
       "legendFormat": "{{event}}"
      }
     ]
    },
    {
     "title": "Operator finish duration",
     "type": "graph",
     "description": "The time consumed when the operator is finished in .99",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_schedule_finish_operators_duration_seconds_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[5m])) by (type, le))",
       "legendFormat": "{{type}}-99%"
      }
     ]
    },
    {
     "title": "Operator step finish duration",
     "type": "graph",
     "description": "The time consumed when the operator step is finished in .99",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_schedule_finish_operator_steps_duration_seconds_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[5m])) by (type, le))",
       "legendFormat": "{{type}}-99%"
      }
     ]
    },
    {
     "title": "Schedulers reach limit",
     "type": "graph",
     "description": "The number of different operators that are failed to be created due to limit configuration",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_schedule_operator_limit{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\"}[1m])) by (type,name)",
       "legendFormat": "{{type}}-{{name}}"
      }
     ]
    },
    {
     "title": "99% operator region size",
     "type": "graph",
     "description": "99% operator region size",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_schedule_operator_region_size_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[5m])) by (type,le))",
       "legendFormat": "{{type,le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Statistics - balance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Store capacity",
     "type": "graph",
     "description": "The capacity size of each TiKV instance",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\", instance=\"$instance\",  type=\"store_capacity\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store available",
     "type": "graph",
     "description": "The available capacity size of each TiKV instance",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\", instance=\"$instance\",  type=\"store_available\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store used",
     "type": "graph",
     "description": "The used capacity size of each TiKV instance",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\", instance=\"$instance\",  type=\"store_used\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store available ratio",
     "type": "graph",
     "description": "It is equal to Store available capacity size over Store capacity size for each TiKV instance",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(pd_scheduler_store_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\", instance=\"$instance\",  type=\"store_available\"}) by (address, store) / sum(pd_scheduler_store_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\",  type=\"store_capacity\"}) by (address, store)",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Size amplification",
     "type": "graph",
     "description": "The size amplification, which is equal to Store Region size over Store used capacity size, of each TiKV instance",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pd_scheduler_store_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\", instance=\"$instance\",  type=\"region_size\"}) by (address, store) / sum(pd_scheduler_store_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\",  type=\"store_used\"}) by (address, store) * 2^20",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store Region score",
     "type": "graph",
     "description": "The Region score of each TiKV instance",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\", instance=\"$instance\",  type=\"region_score\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store leader score",
     "type": "graph",
     "description": "The leader score of each TiKV instance",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\", instance=\"$instance\",  type=\"leader_score\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store Region size",
     "type": "graph",
     "description": "The total Region size of each TiKV instance",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\", instance=\"$instance\",  type=\"region_size\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store leader size",
     "type": "graph",
     "description": " \tThe total leader size of each TiKV instance",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\", instance=\"$instance\",  type=\"leader_size\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store Region count",
     "type": "graph",
     "description": "The Region count of each TiKV instance \t",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\", instance=\"$instance\",  type=\"region_count\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store witness count",
     "type": "graph",
     "description": "The witness count of each TiKV instance",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 111 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\", instance=\"$instance\",  type=\"witness_count\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store leader count",
     "type": "graph",
     "description": "The leader count of each TiKV instance",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\", instance=\"$instance\",  type=\"leader_count\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Statistics - hot write",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Hot Region's leader distribution",
     "type": "graph",
     "description": "The total number of leader Regions under hot write on each TiKV instance",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pd_hotspot_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\", instance=\"$instance\", type=\"hot_write_region_as_leader\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Hot Region's peer distribution",
     "type": "graph",
     "description": "The total number of Regions which are not leader under hot write on each TiKV instance",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pd_hotspot_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\", instance=\"$instance\", type=\"hot_write_region_as_peer\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store write rate bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\", type=\"store_write_rate_bytes\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Total written keys on hot leader Regions",
     "type": "graph",
     "description": "The total bytes of hot write on leader Regions for each TiKV instance",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "pd_hotspot_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\", instance=\"$instance\", type=\"total_write_keys_as_leader\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store write rate keys",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\", type=\"store_write_rate_keys\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store write query",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\", type=\"store_write_query_rate\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Hot cache write entry numbers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pd_hotcache_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", name=\"total_length\", store=~\"store-$store\", type=\"write\"}",
       "legendFormat": "{{store}}"
      }
     ]
    },
    {
     "title": "Selector events",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(pd_scheduler_hot_region{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\", type=~\".*store.*\"}[1m])",
       "legendFormat": "{{type}}-{{store}}"
      }
     ]
    },
    {
     "title": "Direction of hotspot transfer leader",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "- sum(delta(pd_scheduler_hot_region_direction{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\",type=\"transfer-leader\",direction=\"out\",rw=\"write\"}[1m]))by (store)",
       "legendFormat": "store-{{store}}-out"
      },
      {
       "expr": "sum(delta(pd_scheduler_hot_region_direction{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\",type=\"transfer-leader\",direction=\"in\",rw=\"write\"}[1m]))by (store)",
       "legendFormat": "store-{{store}}-in"
      }
     ]
    },
    {
     "title": "Direction of hotspot move peer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "- sum(delta(pd_scheduler_hot_region_direction{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\",type=\"move-peer\",direction=\"out\",rw=\"write\"}[1m]))by (store)",
       "legendFormat": "store-{{store}}-out"
      },
      {
       "expr": "sum(delta(pd_scheduler_hot_region_direction{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\",type=\"move-peer\",direction=\"in\",rw=\"write\"}[1m]))by (store)",
       "legendFormat": "store-{{store}}-in"
      }
     ]
    },
    {
     "title": "Remaining items in Queue",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pd_hotcache_flow_queue_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=\"write\"}",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Statistics - hot read",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Hot Region's peer distribution",
     "type": "graph",
     "description": "The total number of peer Regions under hot read on each TiKV instance",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pd_hotspot_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\", instance=\"$instance\", type=\"hot_read_region_as_peer\"}",
       "legendFormat": "{{address}}-store-{{store}}-peer"
      }
     ]
    },
    {
     "title": "Store read rate bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\", type=\"store_read_rate_bytes\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store read rate keys",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\", type=\"store_read_rate_keys\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Store read query",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_store_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\", type=\"store_read_query_rate\"}",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Direction of hotspot transfer leader",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "- sum(delta(pd_scheduler_hot_region_direction{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\",type=\"transfer-leader\",direction=\"out\",rw=\"read\"}[1m]))by (store)",
       "legendFormat": "store-{{store}}-out"
      },
      {
       "expr": "sum(delta(pd_scheduler_hot_region_direction{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\",type=\"transfer-leader\",direction=\"in\",rw=\"read\"}[1m]))by (store)",
       "legendFormat": "store-{{store}}-in"
      }
     ]
    },
    {
     "title": "Direction of hotspot move peer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "- sum(delta(pd_scheduler_hot_region_direction{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\",type=\"move-peer\",direction=\"out\",rw=\"read\"}[1m]))by (store)",
       "legendFormat": "store-{{store}}-out"
      },
      {
       "expr": "sum(delta(pd_scheduler_hot_region_direction{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\",type=\"move-peer\",direction=\"in\",rw=\"read\"}[1m]))by (store)",
       "legendFormat": "store-{{store}}-in"
      },
      {
       "expr": "- sum(delta(pd_scheduler_hot_region_direction{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\",type=\"move-leader\",direction=\"out\",rw=\"read\"}[1m]))by (store)",
       "legendFormat": "store-{{store}}-out"
      },
      {
       "expr": "sum(delta(pd_scheduler_hot_region_direction{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\",type=\"move-leader\",direction=\"in\",rw=\"read\"}[1m]))by (store)",
       "legendFormat": "store-{{store}}-in"
      }
     ]
    },
    {
     "title": "Hot cache read entry numbers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pd_hotcache_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", name=\"total_length\", store=~\"store-$store\", type=\"read\"}",
       "legendFormat": "{{store}}"
      }
     ]
    },
    {
     "title": "Remaining items in Queue",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pd_hotcache_flow_queue_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=\"read\"}",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Scheduler is running",
     "type": "graph",
     "description": "The current running schedulers",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pd_scheduler_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=\"allow\",instance=\"$instance\"}",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Balance leader movement",
     "type": "graph",
     "description": "The leader movement details among TiKV instances",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "-sum(delta(pd_scheduler_balance_leader{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store-out\", instance=\"$instance\", type=\"move-leader\"}[1m])) by (store)",
       "legendFormat": "store-{{store}}"
      },
      {
       "expr": "sum(delta(pd_scheduler_balance_leader{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store-in\", instance=\"$instance\", type=\"move-leader\"}[1m])) by (store)",
       "legendFormat": "store-{{store}}"
      }
     ]
    },
    {
     "title": "Balance Region movement",
     "type": "graph",
     "description": "The Region movement details among TiKV instances",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "-sum(delta(pd_scheduler_balance_region{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store-out\", instance=\"$instance\", type=\"move-peer\"}[1m])) by (store)",
       "legendFormat": "store-{{store}}"
      },
      {
       "expr": "sum(delta(pd_scheduler_balance_region{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store-in\", instance=\"$instance\", type=\"move-peer\"}[1m])) by (store)",
       "legendFormat": "store-{{store}}"
      }
     ]
    },
    {
     "title": "Balance leader scheduler",
     "type": "graph",
     "description": "The inner status of balance leader scheduler",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pd_scheduler_event_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\", type=\"balance-leader-scheduler\"}[5m])) by (name)",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "sum(rate(pd_scheduler_event_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\", type=\"balance-leader-scheduler\"}[5m]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Balance Region scheduler",
     "type": "graph",
     "description": "The inner status of balance Region scheduler",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pd_scheduler_event_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\", type=\"balance-region-scheduler\"}[5m])) by (name)",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "sum(rate(pd_scheduler_event_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\", type=\"balance-region-scheduler\"}[5m]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Balance Hot Region scheduler",
     "type": "graph",
     "description": "The inner status of balance Hot Region scheduler",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pd_scheduler_event_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\", type=\"balance-hot-region-scheduler\"}[5m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Split Bucket scheduler",
     "type": "graph",
     "description": "The inner status of split bucket scheduler",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pd_scheduler_event_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\", type=\"split-bucket-scheduler\"}[5m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Balance Direction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_scheduler_balance_direction{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\"}[1m])) by (type, source, target)",
       "legendFormat": "{{source}}-{{target}}-{{type}}"
      }
     ]
    },
    {
     "title": "Patrol Region time",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pd_checker_patrol_regions_time{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Rule checker",
     "type": "graph",
     "description": "The replica checker's status",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pd_checker_event_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\", type=\"rule_checker\"}[1m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Replica checker",
     "type": "graph",
     "description": "The replica checker's status",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pd_checker_event_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\", type=\"replica_checker\"}[1m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Region merge checker",
     "type": "graph",
     "description": "The merge checker's status",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pd_checker_event_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\", type=\"merge_checker\"}[1m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Filter source",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_schedule_filter{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\", action=\"filter-source\", type!=\"store-state-tombstone-filter\"}[1m])) by (source, type, scope)",
       "legendFormat": "{{scope}}-store-{{source}}-{{type}}"
      }
     ]
    },
    {
     "title": "Filter target",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_schedule_filter{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\", action=\"filter-target\", type!=\"store-state-tombstone-filter\"}[1m])) by (target, type, scope)",
       "legendFormat": "{{scope}}-store-{{target}}-{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Scatter and Splitter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "scatter operator event",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_schedule_scatter_operators_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\", type=\"skip\"}[1m])) by (event)",
       "legendFormat": "skip-{{event}}"
      },
      {
       "expr": "delta(pd_schedule_scatter_operators_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\", type=\"fail\"}[1m])",
       "legendFormat": "fail"
      },
      {
       "expr": "delta(pd_schedule_scatter_operators_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\", type=\"success\"}[1m])",
       "legendFormat": "success"
      }
     ]
    },
    {
     "title": "scatter store selection",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_schedule_scatter_distribution{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\",engine=\"tikv\",is_leader=\"false\"}[1m])) by (store)",
       "legendFormat": "peer-{{store}}"
      },
      {
       "expr": "sum(delta(pd_schedule_scatter_distribution{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\",engine=\"tikv\",is_leader=\"true\"}[1m])) by (store)",
       "legendFormat": "leader-{{store}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "gRPC Completed commands rate",
     "type": "graph",
     "description": "The rate of completing each kind of gRPC commands",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handling_seconds_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\"}[1m])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "gRPC 99% Completed commands duration",
     "type": "graph",
     "description": "The time consumed of completing each kind of gRPC commands in .99",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\"}[5m])) by (grpc_method, le))",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "HTTP Completed commands rate",
     "type": "graph",
     "description": "The rate of completing each kind of HTTP requests",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pd_service_audit_handling_seconds_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\"}[1m])) by (service,ip)",
       "legendFormat": "{{service}}-{{ip}}"
      }
     ]
    },
    {
     "title": "HTTP 99% Completed commands duration",
     "type": "graph",
     "description": "The time consumed of completing each kind of HTTP request in .99",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_service_audit_handling_seconds_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=\"$instance\"}[5m])) by (service, le))",
       "legendFormat": "{{service}}"
      }
     ]
    }
   ]
  },
  {
   "title": "etcd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "MVCC DB total size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "etcd_debugging_mvcc_db_total_size_in_bytes{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", job=\"pd\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Handle transactions rate",
     "type": "graph",
     "description": "The rate of handling etcd transactions",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pd_txn_handle_txns_duration_seconds_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[5m])) by (instance, result)",
       "legendFormat": "{{instance}} : {{result}}"
      }
     ]
    },
    {
     "title": "99% Handle transactions duration",
     "type": "graph",
     "description": "The time consumed of handling etcd transactions in .99",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_txn_handle_txns_duration_seconds_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[5m])) by (instance, result, le))",
       "legendFormat": "{{instance}} {{result}}"
      }
     ]
    },
    {
     "title": "99% Peer round trip time seconds",
     "type": "graph",
     "description": "The latency of the network in .99",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(etcd_network_peer_round_trip_time_seconds_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[5m])) by (instance, To, le))",
       "legendFormat": "{{instance}} - {{To}}"
      }
     ]
    },
    {
     "title": "99% WAL fsync duration",
     "type": "graph",
     "description": "The time consumed of writing WAL into the persistent storage in .99",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[5m])) by (instance, le))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "etcd disk wal fsync rate",
     "type": "graph",
     "description": "The rate of writing WAL into the persistent storage",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "delta(etcd_disk_wal_fsync_duration_seconds_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", job=\"pd\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "99% backend commit duration",
     "type": "graph",
     "description": "The time consumed of committing an incremental snapshot of its most recent changes to the persistent storage in .99",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[5m])) by (instance, le))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "etcd disk backend commit rate",
     "type": "graph",
     "description": "The rate of committing an incremental snapshot of its most recent changes to the persistent storage",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "delta(etcd_disk_backend_commit_duration_seconds_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Raft term",
     "type": "graph",
     "description": "The current term of Raft",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pd_server_etcd_state{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=\"term\"}",
       "legendFormat": "{{instance}} - {{job}}"
      }
     ]
    },
    {
     "title": "Raft committed index",
     "type": "graph",
     "description": "The last committed index of Raft",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pd_server_etcd_state{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=\"committedIndex\"}",
       "legendFormat": "{{instance}} - {{job}}"
      }
     ]
    },
    {
     "title": "Raft applied index",
     "type": "graph",
     "description": " \tThe last applied index of Raft",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pd_server_etcd_state{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=\"appliedIndex\"}",
       "legendFormat": "{{instance}} - {{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TiDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "PD server TSO handle time",
     "type": "graph",
     "description": "The time consumed of handling TiDB requests",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 114 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(pd_server_handle_tso_duration_seconds_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[30s])) by (type, le))",
       "legendFormat": "90% tso"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_server_handle_tso_duration_seconds_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[30s])) by (type, le))",
       "legendFormat": "99% tso"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(pd_server_handle_tso_duration_seconds_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[30s])) by (type, le))",
       "legendFormat": "99.9% tso"
      },
      {
       "expr": "histogram_quantile(0.99999, sum(rate(pd_server_handle_tso_duration_seconds_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[30s])) by (type, le))",
       "legendFormat": "99.999% tso"
      }
     ]
    },
    {
     "title": "Handle requests duration",
     "type": "graph",
     "description": "The time consumed of handling TiDB requests",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 114 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.98, sum(rate(pd_client_request_handle_requests_duration_seconds_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[30s])) by (type, le))",
       "legendFormat": "{{type}} 98th percentile"
      },
      {
       "expr": "avg(rate(pd_client_request_handle_requests_duration_seconds_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[30s])) by (type) /  avg(rate(pd_client_request_handle_requests_duration_seconds_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[30s])) by (type)",
       "legendFormat": "{{type}} average"
      }
     ]
    },
    {
     "title": "Handle requests count",
     "type": "graph",
     "description": "The count of TSO grpc requests",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 123 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pd_server_handle_tso_duration_seconds_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (type)",
       "legendFormat": "tso request/secs"
      }
     ]
    },
    {
     "title": "Tso Request batch size",
     "type": "graph",
     "description": "The batch size of TiDB tso requests",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 123 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_client_request_handle_tso_batch_size_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (le))",
       "legendFormat": "0.99 batch size"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(pd_client_request_handle_tso_batch_size_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (le))",
       "legendFormat": "0.90 batch size"
      },
      {
       "expr": "sum(delta(pd_client_request_handle_tso_batch_size_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) / sum(delta(pd_client_request_handle_tso_batch_size_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m]))",
       "legendFormat": "avg batch size"
      }
     ]
    }
   ]
  },
  {
   "title": "Heartbeat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Heartbeat region event QPS",
     "type": "graph",
     "description": "The heartbeat update cache or kv OPS",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pd_cluster_region_event{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\", instance=\"$instance\"}[1m])) by (address, store, event)",
       "legendFormat": "{{event}}"
      }
     ]
    },
    {
     "title": "99% Region heartbeat handle latency",
     "type": "graph",
     "description": "The region heartbeat handle duration in .99",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_scheduler_handle_region_heartbeat_duration_seconds_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\"}[1m])) by (address, store, le))",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "TiKV side heartbeat statistics",
     "type": "graph",
     "description": "The total number of PD heartbeat messages and pending status",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_pd_heartbeat_message_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=~\"$tidb_cluster.*\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "tikv_pd_pending_heartbeat_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=~\"$tidb_cluster.*\"}",
       "legendFormat": "pending-{{instance}}"
      }
     ]
    },
    {
     "title": "Region heartbeat report",
     "type": "graph",
     "description": "The count of the heartbeats which each TiKV instance reports to PD",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_scheduler_region_heartbeat{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\", instance=\"$instance\", type=\"report\", status=\"ok\"}[1m])) by (address, store)",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Region schedule push",
     "type": "graph",
     "description": "The count of the corresponding schedule commands which PD sends to each TiKV instance",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pd_scheduler_region_heartbeat{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\", type=\"push\",instance=\"$instance\"}[5m])*60) by (address, store, status)",
       "legendFormat": "{{address}}-{{status}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Region heartbeat report error",
     "type": "graph",
     "description": "The count of the heartbeats with the error status",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_scheduler_region_heartbeat{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\", instance=\"$instance\", type=\"report\", status=\"err\"}[1m])) by (address, store)",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Region heartbeat report active",
     "type": "graph",
     "description": "The count of the heartbeats with the ok status",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_scheduler_region_heartbeat{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\", instance=\"$instance\", type=\"report\", status=\"bind\"}[1m])) by (address, store)",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "99% store heartbeat handle duration",
     "type": "graph",
     "description": "The store heartbeat handle duration in .99",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_scheduler_handle_store_heartbeat_duration_seconds_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\"}[1m])) by (address, store, le))",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Heartbeat stream report",
     "type": "graph",
     "description": "The count of the message which PD send to each TiKV instance",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_hbstream_region_message{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\", instance=\"$instance\", type=\"push\", status=\"ok\"}[1m])) by (address, store)",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Heartbeat stream report error",
     "type": "graph",
     "description": "The count of the message which PD send to each TiKV instance with error status",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(delta(pd_hbstream_region_message{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", store=~\"$store\", instance=\"$instance\", type=\"push\", status=\"err\"}[1m])) by (address, store)",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "99% Bucket Report Interval",
     "type": "graph",
     "description": "The Interval of TIkv bucket report interval",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_server_bucket_report_interval_seconds_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=~\"$tidb_cluster.*\", store=~\"$store\"}[1m])) by (address, store, le))",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    },
    {
     "title": "Bucket Report State",
     "type": "graph",
     "description": "The State of Bucket Report",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pd_server_bucket_report{k8s_cluster=\"$k8s_cluster\", tidb_cluster=~\"$tidb_cluster.*\", store=~\"$store\", instance=\"$instance\"}[1m])) by (address, store, type,status)",
       "legendFormat": "{{address}}-store-{{store}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Heartbeat distribution ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Read Region Byte",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(delta(pd_scheduler_read_byte_hist_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Write Region Byte",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(delta(pd_scheduler_write_byte_hist_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Read Region Key",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(delta(pd_scheduler_read_key_hist_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Write Region Key",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(delta(pd_scheduler_write_key_hist_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Store Heartbeat Interval",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(delta(pd_scheduler_store_heartbeat_interval_hist_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Region Heartbeat Interval",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(delta(pd_scheduler_region_heartbeat_interval_hist_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Bucket Report Interval",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(delta(pd_server_bucket_report_interval_seconds_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=~\"$tidb_cluster.*\", instance=~\"$instance\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Hot Degree of Bucket",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(delta(pd_scheduler_buckets_hot_degree_hist_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=~\"$tidb_cluster.*\", instance=~\"$instance\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Region storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Syncer index",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 213 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pd_region_syncer_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=\"sync_index\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "History last index",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 213 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pd_region_syncer_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=\"last_index\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}