{
 "title": "Nginx监控总览",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Nginx主机",
    "query": {
     "query": "label_values(nginx_vts_info,instance)"
    }
   },
   {
    "name": "interval",
    "label": "图表时间间隔",
    "query": "15s,30s,1m,2m,5m,10m,30m,1h,3h,6h"
   },
   {
    "name": "namespace",
    "label": "Nginx名称空间",
    "query": {
     "query": "label_values(nginx_vts_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "当前连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nginx_vts_main_connections{instance=~\"$host\", status=~\"active\"}) by (namespace)",
     "legendFormat": "总数 {{  namespace  }}"
    },
    {
     "expr": "sum(nginx_vts_main_connections{instance=~\"$host\", status=~\"writing\"}) by (namespace)",
     "legendFormat": "写入 {{  namespace  }}"
    },
    {
     "expr": "sum(nginx_vts_main_connections{instance=~\"$host\", status=~\"reading\"}) by (namespace)",
     "legendFormat": "读取 {{  namespace  }}"
    },
    {
     "expr": "sum(nginx_vts_main_connections{instance=~\"$host\", status=~\"waiting\"}) by (namespace)",
     "legendFormat": "驻留 {{  namespace  }}"
    }
   ]
  },
  {
   "title": "每秒请求数（按域名）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_server_requests_total{instance=~\"$host\",host!~\"_|\\\\*\",code!=\"total\"}[1m])) by (host)",
     "legendFormat": "{{  code  }}"
    }
   ]
  },
  {
   "title": "状态码错误率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(nginx_vts_upstream_requests_total{instance=~\"$host\", code=~\"4xx|5xx\", upstream!=\"::nogroups\"} [30s])) by (upstream) / sum(rate(nginx_vts_upstream_requests_total{instance=~\"$host\", code=~\"total\", upstream!=\"::nogroups\"} [30s])) by (upstream)) * 100",
     "legendFormat": "{{  upstream  }}"
    }
   ]
  },
  {
   "title": "状态码错误数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nginx_vts_upstream_requests_total{instance=~\"$host\", code=~\"4xx|5xx\", upstream!=\"::nogroups\"} - (nginx_vts_upstream_requests_total{instance=~\"$host\", code=~\"4xx|5xx\", upstream!=\"::nogroups\"} offset 30s)",
     "legendFormat": "{{  upstream  }}"
    }
   ]
  },
  {
   "title": "服务request耗时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(nginx_vts_upstream_request_seconds{instance=~\"$host\",upstream!=\"::nogroups\"} * 1000) by (upstream)",
     "legendFormat": "{{  upstream  }}"
    }
   ]
  },
  {
   "title": "服务response耗时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(nginx_vts_upstream_response_seconds{instance=~\"$host\",upstream!=\"::nogroups\"} * 1000) by (upstream)",
     "legendFormat": "{{  upstream  }}"
    }
   ]
  },
  {
   "title": "接收速率（按域名）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_server_bytes_total{instance=~\"$host\",direction=\"in\",host!~\"_|\\\\*\"} [1m])) by (host)",
     "legendFormat": "{{  host  }}"
    }
   ]
  },
  {
   "title": "每秒请求数（按返回值）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_server_requests_total{instance=~\"$host\",host=\"*\",code!=\"total\"}[1m])) by (code)",
     "legendFormat": "{{  code  }}"
    }
   ]
  },
  {
   "title": "域名request耗时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(nginx_vts_server_request_seconds{instance=~\"$host\",host!~\"_|\\\\*\"} * 1000) by (host)",
     "legendFormat": "{{  host  }}"
    }
   ]
  },
  {
   "title": "发送速率（按域名）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_server_bytes_total{instance=~\"$host\",direction=\"out\",host!~\"_|\\\\*\"} [1m])) by (host)",
     "legendFormat": "{{  host  }}"
    }
   ]
  },
  {
   "title": "接收/发送 速率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_server_bytes_total{instance=~\"$host\",direction=\"in\",host=\"*\"} [1m])) by (namespace)",
     "legendFormat": "receive {{  namespace  }}"
    },
    {
     "expr": "sum(rate(nginx_vts_server_bytes_total{instance=~\"$host\",direction=\"out\",host=\"*\"} [1m])) by (namespace)",
     "legendFormat": "sent {{  namespace  }}"
    }
   ]
  }
 ]
}